#!/usr/bin/env python3
"""install_graphify_hooks_safe.py -- apply the G5P.0c process-hygiene patch to the
graphify post-commit hook (TRACKED mitigation; the hook itself lives in untracked
.git/hooks and is regenerated by `graphify hook install`).

WHY THIS EXISTS (G5P.0d durability audit, 2026-06-11):
  The graphify-installed post-commit hook detaches a full-core graph rebuild per
  commit with (a) NO single-instance guard -- rapid commits stack concurrent
  rebuilds -- and (b) a 600s timeout gated on `hasattr(signal, 'SIGALRM')`,
  which is unix-only, so hung rebuilds on Windows live FOREVER. The operator hit
  stale full-core pythons. The durable fix belongs in the graphify package's
  hook template (graphify/hooks.py, repo: Documents/graphify, uv tool
  `graphifyy`); until that ships, THIS script makes any machine reproducible:

    python scripts/install_graphify_hooks_safe.py        # after `graphify hook install`

  Fresh clone flow: `graphify hook install` -> run this script once. Idempotent;
  safe to re-run after every hook reinstall.

WHAT THE PATCH ADDS (inside the hook's embedded rebuild script):
  1. newest-wins pidfile guard (~/.cache/graphify-rebuild.pid): a new commit's
     rebuild tree-kills the superseded in-flight one. The kill is PID-validated
     (taskkill filtered to IMAGENAME python.exe on Windows; plain SIGTERM on
     unix) so a recycled PID cannot hit an unrelated process class.
  2. cross-platform watchdog: daemon threading.Timer hard-exits the rebuild at
     GRAPHIFY_REBUILD_TIMEOUT (default 600s) -- works on Windows where the
     template's SIGALRM guard is silently inert.

Exit codes: 0 patched-or-already-patched | 2 hook missing | 3 anchors missing
(template changed upstream -- re-audit) | 4 verification failed (nothing written).
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

SENTINEL = "G5P.0c: newest-wins single-instance guard"

ANCHOR_PRINT = "print(f'[graphify hook] {len(changed)} file(s) changed - rebuilding graph...')"

ANCHOR_SIGALRM = """    _timeout = int(os.environ.get('GRAPHIFY_REBUILD_TIMEOUT', '600'))
    if _timeout > 0 and hasattr(signal, 'SIGALRM'):
        signal.signal(signal.SIGALRM, lambda *_: (_ for _ in ()).throw(TimeoutError(f'graphify rebuild exceeded {_timeout}s')))
        signal.alarm(_timeout)"""

PIDFILE_GUARD = """# G5P.0c: newest-wins single-instance guard -- rapid commits were stacking
# full-core detached rebuilds (operator hit stale pythons). The latest commit
# supersedes any in-flight rebuild (full idempotent scan of the working tree).
import subprocess as _sp
_pidfile = Path(os.path.expanduser('~')) / '.cache' / 'graphify-rebuild.pid'
try:
    if _pidfile.exists():
        _old = _pidfile.read_text(encoding='utf-8').strip()
        if _old.isdigit() and int(_old) != os.getpid():
            if os.name == 'nt':
                _sp.run(['taskkill', '/PID', _old, '/T', '/F', '/FI', 'IMAGENAME eq python.exe'], capture_output=True)
            else:
                os.kill(int(_old), signal.SIGTERM)
    _pidfile.parent.mkdir(parents=True, exist_ok=True)
    _pidfile.write_text(str(os.getpid()), encoding='utf-8')
except Exception:
    pass

""" + ANCHOR_PRINT

CROSS_PLATFORM_WATCHDOG = """    _timeout = int(os.environ.get('GRAPHIFY_REBUILD_TIMEOUT', '600'))
    if _timeout > 0:
        # G5P.0c: SIGALRM is unix-only (silently inert on Windows -- hung rebuilds
        # lived forever); a daemon timer hard-exits cross-platform instead.
        import threading as _th
        _wd = _th.Timer(_timeout, lambda: (print(f'[graphify hook] rebuild exceeded {_timeout}s - killed by watchdog'), os._exit(1)))
        _wd.daemon = True
        _wd.start()"""


def patch_hook_text(text: str) -> tuple[str, str]:
    """Return (new_text, status). status: patched | already-patched | anchor-missing."""
    if SENTINEL in text:
        return text, "already-patched"
    if ANCHOR_PRINT not in text or ANCHOR_SIGALRM not in text:
        return text, "anchor-missing"
    text = text.replace(ANCHOR_PRINT, PIDFILE_GUARD, 1)
    text = text.replace(ANCHOR_SIGALRM, CROSS_PLATFORM_WATCHDOG, 1)
    return text, "patched"


def verify_embedded_script(text: str) -> bool:
    """The hook embeds its rebuild script as _src = '''...'''; it must compile."""
    m = re.search(r"_src = '''(.*?)'''", text, re.S)
    if not m:
        return False
    try:
        compile(m.group(1), "<hook-embedded>", "exec")
        return True
    except SyntaxError:
        return False


def locate_hook() -> Path | None:
    try:
        git_dir = subprocess.run(
            ["git", "rev-parse", "--git-dir"], capture_output=True, text=True, check=True
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None
    hook = Path(git_dir) / "hooks" / "post-commit"
    return hook if hook.is_file() else None


def main() -> int:
    hook = locate_hook()
    if hook is None:
        print("post-commit hook not found - run `graphify hook install` first, then re-run this script.")
        return 2
    original = hook.read_text(encoding="utf-8")
    if "graphify-hook-start" not in original:
        print(f"{hook} is not a graphify-installed hook (marker missing) - nothing done.")
        return 3
    new_text, status = patch_hook_text(original)
    if status == "already-patched":
        print(f"{hook}: hygiene patch already present - nothing to do.")
        return 0
    if status == "anchor-missing":
        print(
            f"{hook}: expected template anchors not found - the graphify hook template "
            "changed upstream. Re-audit scripts/install_graphify_hooks_safe.py against "
            "the new template (or the upstream fix may already include the guard)."
        )
        return 3
    if not verify_embedded_script(new_text):
        print(f"{hook}: patched embedded script failed to compile - NOT writing. Report this.")
        return 4
    hook.write_text(new_text, encoding="utf-8", newline="\n")
    print(f"{hook}: hygiene patch applied (pidfile newest-wins guard + cross-platform watchdog).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
